import { useMemo } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { Share2, Sparkles, Trophy } from "lucide-react";
import { useApp } from "../store/AppStore";
import { getCourse } from "../data/courses";
import { Avatar, Card } from "../components/ui";
import { ScorecardGrid } from "../components/ScorecardGrid";
import { analyzeRound } from "../lib/insights";
import { coursePar, formatToPar, playerTotals } from "../lib/scoring";
import { formatDate } from "../lib/format";

export function RoundFinish() {
  const navigate = useNavigate();
  const location = useLocation();
  const { rounds, showToast } = useApp();

  const roundId = (location.state as { roundId?: string } | null)?.roundId;
  const round = useMemo(
    () =>
      rounds.find((r) => r.id === roundId) ??
      [...rounds].sort((a, b) => b.endedAt.localeCompare(a.endedAt))[0],
    [rounds, roundId]
  );

  if (!round) {
    navigate("/", { replace: true });
    return null;
  }

  const course = getCourse(round.courseId);
  const board = round.players
    .map((p) => ({ player: p, ...playerTotals(round.scores[p.id] ?? [], course) }))
    .sort((a, b) => a.toPar - b.toPar || a.strokes - b.strokes);
  const insights = analyzeRound(round, course, "me");
  const winner = board[0];

  const share = async () => {
    const lines = [
      `⛓️ Chains — ${course.name}, ${formatDate(round.startedAt)}`,
      ...board.map(
        (b, i) =>
          `${i + 1}. ${b.player.name}: ${b.strokes} (${formatToPar(b.toPar)})`
      )
    ];
    try {
      await navigator.clipboard.writeText(lines.join("\n"));
      showToast("Results copied to clipboard");
    } catch {
      showToast("Couldn't access clipboard");
    }
  };

  return (
    <div className="pb-12">
      <div className="px-4 pt-14 text-center">
        <div className="anim-pop mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-accent/15 text-accent">
          <Trophy size={30} />
        </div>
        <h1 className="text-[30px] font-bold">Round complete</h1>
        <p className="mt-1 text-[15px] text-sub">
          {course.name} · par {coursePar(course)} · {formatDate(round.startedAt)}
        </p>
      </div>

      <div className="px-4 pt-6">
        <Card className="divide-y divide-sep">
          {board.map((row, i) => (
            <div key={row.player.id} className="flex items-center gap-3 p-4">
              <span
                className={`w-6 text-center text-[17px] font-bold ${
                  i === 0 ? "text-accent" : "text-sub"
                }`}
              >
                {i + 1}
              </span>
              <Avatar name={row.player.name} size={40} />
              <div className="flex-1">
                <p className="text-[16px] font-semibold">{row.player.name}</p>
                <p className="text-[13px] text-sub">{row.strokes} throws</p>
              </div>
              <span
                className={`text-[24px] font-bold tabular-nums ${
                  row.toPar < 0 ? "text-birdie" : row.toPar === 0 ? "text-sub" : ""
                }`}
              >
                {formatToPar(row.toPar)}
              </span>
            </div>
          ))}
        </Card>
        {board.length > 1 && (
          <p className="pt-2 text-center text-[13px] text-sub">
            {winner.player.name.split(" ")[0]} takes the round
            {board[1].toPar > winner.toPar
              ? ` by ${board[1].toPar - winner.toPar}`
              : " on a tiebreak"}
          </p>
        )}
      </div>

      <div className="px-4 pt-5">
        <ScorecardGrid round={round} course={course} />
      </div>

      {insights.length > 0 && (
        <div className="px-4 pt-5">
          <Card className="overflow-hidden">
            <div className="flex items-center gap-2 border-b border-sep px-4 py-3">
              <Sparkles size={16} className="text-accent-hi" />
              <p className="text-[15px] font-bold">AI Insights</p>
              <span className="ml-auto rounded-full bg-accent/15 px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide text-accent">
                Beta
              </span>
            </div>
            <div className="divide-y divide-sep">
              {insights.map((ins) => (
                <div key={ins.title} className="px-4 py-3.5">
                  <p className="text-[14px] font-semibold">{ins.title}</p>
                  <p className="mt-1 text-[13px] leading-snug text-sub">
                    {ins.body}
                  </p>
                </div>
              ))}
            </div>
            <p className="px-4 pb-3 pt-1 text-[11px] text-sub">
              Generated by Chains AI from this round's scores.
            </p>
          </Card>
        </div>
      )}

      <div className="space-y-2.5 px-4 pt-6">
        <button
          onClick={share}
          className="press flex h-[50px] w-full items-center justify-center gap-2 rounded-full bg-card text-[16px] font-semibold"
        >
          <Share2 size={17} /> Share results
        </button>
        <button
          onClick={() => navigate("/", { replace: true })}
          className="press h-[50px] w-full rounded-full bg-accent text-[16px] font-bold text-white"
        >
          Done
        </button>
      </div>
      <p className="pt-3 text-center text-[12px] text-sub">
        Saved to your round history automatically.
      </p>
    </div>
  );
}
